[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
auction_escrow = "7x3UJv4wHouZpPDJ6Mf6KQBgGCiPuFN9oF1dziuMx6y8"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
